# .travis.yml
language: node_js
node_js:
  - "8.10.0"
branches:
  only:
    - master
email:
  on_failure: change
  on_success: never
cache:
  directories:
    - node_modules
git:
  depth: 20
script:
  - npm run test
  - npm run prod
after_success:
  - npm run coveralls